name: Export GCP predefined roles and permissions

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: write
  id-token: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Authenticate
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          project_id: ${{ secrets.project_id }}
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          request_reason: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}
      - name: Export
        uses: ./.github/actions/exporter
        with:
          output_file: pages/roles.json
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pages/roles.json
          git commit -m "Update exported predefined roles and permissions"
          git push
